# Generated by Django 5.2.16 on 2026-09-16 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DemoScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Operación Atlántico", max_length=80),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("duration", models.PositiveIntegerField(default=150)),
                ("configuration", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="RateLimit",
            fields=[
                (
                    "key",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("window", models.BigIntegerField(default=0)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_session", models.CharField(db_index=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mission.demoscenario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunicationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elapsed", models.PositiveIntegerField()),
                ("data", models.JSONField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mission.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissionState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.JSONField(default=dict)),
                ("running", models.BooleanField(db_index=True, default=False)),
                ("speed", models.PositiveSmallIntegerField(default=1)),
                ("revision", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live",
                        to="mission.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelemetrySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elapsed", models.PositiveIntegerField()),
                ("data", models.JSONField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mission.mission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MissionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("elapsed", models.PositiveIntegerField()),
                ("kind", models.CharField(max_length=24)),
                ("message", models.CharField(max_length=240)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mission.mission",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mission", "sequence"), name="unique_mission_event"
                    )
                ],
            },
        ),
    ]
