# Generated by Django 5.2.16 on 2026-09-16 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="missionstate",
            name="generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AIFlight",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("generation", models.PositiveIntegerField()),
                ("incident", models.PositiveIntegerField()),
                ("key", models.CharField(max_length=160)),
                ("job_id", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(default="PENDING", max_length=16)),
                ("snapshot", models.JSONField(default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mission.mission",
                    ),
                ),
            ],
        ),
    ]
