# Generated by Django 5.2.16 on 2026-09-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission", "0002_missionstate_generation_aiflight"),
    ]

    operations = [
        migrations.AddField(
            model_name="demoscenario",
            name="fleet_size",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="demoscenario",
            name="scenario_key",
            field=models.CharField(default="atlantic", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="demoscenario",
            constraint=models.CheckConstraint(
                condition=models.Q(("fleet_size__gte", 1), ("fleet_size__lte", 3)),
                name="fleet_size_range",
            ),
        ),
    ]
