# Generated by Django 5.2.16 on 2026-09-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission", "0002_missionstate_generation_aiflight"),
    ]

    operations = [
        migrations.AddField(
            model_name="demoscenario",
            name="scenario_key",
            field=models.CharField(default="atlantic", max_length=32),
        ),
    ]
