# Generated by Django 5.2.16 on 2026-09-18 00:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mission", "0003_demoscenario_fleet_size_demoscenario_scenario_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebriefFlight",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("generation", models.PositiveIntegerField()),
                ("key", models.CharField(max_length=160)),
                ("job_id", models.CharField(blank=True, max_length=64)),
                ("status", models.CharField(default="PENDING", max_length=16)),
                ("snapshot", models.JSONField(default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("source", models.CharField(default="LOCAL", max_length=8)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "next_attempt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mission.mission",
                    ),
                ),
            ],
        ),
    ]
