# Generated by Django 5.2.10 on 2026-09-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0004_debriefflight'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='ai_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
